name: RealMines
description: Brand new, simple and efficient mine management plugin.
author: JoseGamer_PT
version: 6-03-2021 Build 2
website: www.spigotmc.org/members/josegamer_pt.40267/
main: josegamerpt.realmines.RealMines
api-version: 1.14
depend: [WorldEdit]
softdepend: [Multiverse-Core]
load: POSTWORLD
